version: 1

models:
  - name: raw_pizza_orders
    columns:
      - name: pizza_type
        tests:
          - not_null
          - relationships:
              to: ref('pizza_prices')
              field: pizza_type